name: aplicacion_minerd
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_sound: ^9.1.11
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  flutter_html: any
  geocoding: ^3.0.0
  latlong2: ^0.8.1
  provider: ^6.1.2
  permission_handler: ^11.3.1
  http: ^0.13.6
  google_maps_flutter: ^2.6.0
  geolocator: ">=12.0.0 <13.0.1"
  path_provider: ^2.0.7
  image_picker: ^1.1.2
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.6
  sqflite: ^2.0.0+4
  path: ^1.8.0
  carousel_slider: ^4.0.0
  vibration: ^1.7.4
  video_player: ^2.2.11
  concentric_transition: ^1.0.1+1
  google_fonts: ^4.0.3
  animations: ^2.0.0
  fan_floating_menu: any
  awesome_drawer_bar: any
  flutter_zoom_drawer: ^2.1.0
  flutter_bloc: ^8.0.0
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 4.1.1+1
  from_css_color: 2.0.0
  go_router: ^7.1.1
  intl: 0.18.1
  json_path: 0.6.2
  dart_ipify: ^1.1.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  retrofit: ^4.0.3
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile_placeholder.png
    - assets/images/profile_placeholde.png
    - assets/images/educacion.png
    - assets/images/prueba.png
    - assets/images/docente.png
    - assets/images/logo_remolacha.png
    - assets/videos/delete.mp4
    - assets/videos/list_unfine.mp4
    - assets/icons/custom_icon.svg
    - assets/icons/icon-menu.svg
