name: aplicacion_minerd
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  provider: ^6.1.2
  permission_handler: ^11.3.1
  flutter_sound: ^9.1.11
  shared_preferences: ^2.0.6
  http: ^0.13.6
  google_maps_flutter: ^2.6.0
  geolocator: ^12.0.0
  path_provider: ^2.0.7
  image_picker: ^1.1.2
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.6
  sqflite: ^2.0.0+4
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Directorio para imágenes
    - assets/audio/  # Directorio para archivos de audio
